In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('train_file.csv')

In [3]:
df.head()

,Patient_ID,YEAR,LocationDesc,Subtopic,Greater_Risk_Question,Description,Sample_Size,Sex,Race,Grade,GeoLocation,QuestionCode,StratID1,StratID2,StratID3,StratificationType,Greater_Risk_Probability
0,1,1995,"Houston, TX",1,Ever used cocaine,"any form of cocaine, such as powder, crack, or...",335.0,Female,Hispanic or Latino,4,"(29.760427, -95.369803)",H49,1,4,0,Local,7.4793
1,2,1997,"Houston, TX",0,Currently drank alcohol,"at least one drink of alcohol, on at least 1 d...",382.0,Total,Black or African American,4,"(29.760427, -95.369803)",H42,0,3,0,Local,49.6852
2,3,1993,Nevada,0,Had their first drink of alcohol before age 13...,other than a few sips,196.0,Female,White,0,"(39.493240390000494, -117.07184056399967)",H41,1,6,2,State,47.8132
3,4,2017,Pennsylvania,1,Ever used cocaine,"any form of cocaine, such as powder, crack, or...",104.0,Male,Asian,4,"(40.79373015200048, -77.86070029399963)",H49,2,2,0,State,3.4554
4,5,2007,"San Francisco, CA",1,Ever took steroids without a doctor's prescrip...,"pills or shots, one or more times during their...",100.0,Female,Multiple Race,4,"(37.77493, -122.419416)",H55,1,7,0,Local,0.0000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55399 entries, 0 to 55398
Data columns (total 17 columns):
Patient_ID                  55399 non-null int64
YEAR                        55399 non-null int64
LocationDesc                55399 non-null object
Subtopic                    55399 non-null int64
Greater_Risk_Question       55399 non-null object
Description                 55399 non-null object
Sample_Size                 55399 non-null float64
Sex                         55399 non-null object
Race                        55399 non-null object
Grade                       55399 non-null int64
GeoLocation                 52098 non-null object
QuestionCode                55399 non-null object
StratID1                    55399 non-null int64
StratID2                    55399 non-null int64
StratID3                    55399 non-null int64
StratificationType          55399 non-null object
Greater_Risk_Probability    55399 non-null float64
dtypes: float64(2), int64(7), object(8)
memory usage: 7.2+ MB

In [5]:
df.drop(columns=['GeoLocation'], inplace=True)

In [6]:
df.describe(include='all')

,Patient_ID,YEAR,LocationDesc,Subtopic,Greater_Risk_Question,Description,Sample_Size,Sex,Race,Grade,QuestionCode,StratID1,StratID2,StratID3,StratificationType,Greater_Risk_Probability
count,55399.000000,55399.000000,55399,55399.000000,55399,55399,55399.000000,55399,55399,55399.000000,55399,55399.000000,55399.000000,55399.000000,55399,55399.000000
unique,NaN,NaN,91,NaN,20,20,NaN,3,8,NaN,20,NaN,NaN,NaN,5,NaN
top,NaN,NaN,United States,NaN,Currently used marijuana,"also called grass, pot, or weed, one or more t...",NaN,Total,Total,NaN,H48,NaN,NaN,NaN,State,NaN
freq,NaN,NaN,2276,NaN,4421,4421,NaN,22057,22252,NaN,4421,NaN,NaN,NaN,31878,NaN
mean,27700.000000,2007.674308,NaN,0.747270,NaN,NaN,566.206339,NaN,NaN,2.238488,NaN,0.897327,2.718479,1.708695,NaN,24.365664
std,15992.458118,6.906621,NaN,0.434581,NaN,NaN,1148.727489,NaN,NaN,1.494005,NaN,0.826494,2.516150,1.448596,NaN,20.492551
min,1.000000,1991.000000,NaN,0.000000,NaN,NaN,50.000000,NaN,NaN,0.000000,NaN,0.000000,0.000000,0.000000,NaN,0.000000
25%,13850.500000,2003.000000,NaN,0.000000,NaN,NaN,165.000000,NaN,NaN,1.000000,NaN,0.000000,0.000000,0.000000,NaN,8.280050
50%,27700.000000,2009.000000,NaN,1.000000,NaN,NaN,275.000000,NaN,NaN,2.000000,NaN,1.000000,3.000000,2.000000,NaN,17.555600
75%,41549.500000,2013.000000,NaN,1.000000,NaN,NaN,560.500000,NaN,NaN,4.000000,NaN,2.000000,6.000000,3.000000,NaN,35.430750
max,55399.000000,2017.000000,NaN,1.000000,NaN,NaN,53664.000000,NaN,NaN,4.000000,NaN,2.000000,7.000000,4.000000,NaN,99.449400

In [7]:
Greater_Risk_Question = df.Greater_Risk_Question.unique()
Greater_Risk_Question

array(['Ever used cocaine', 'Currently drank alcohol',
       'Had their first drink of alcohol before age 13 years',
       "Ever took steroids without a doctor's prescription",
       'Ever used inhalants',
       'Were offered, sold, or given an illegal drug on school property',
       'Ever used marijuana', 'Ever used heroin', 'Ever drank alcohol',
       'Currently used marijuana', 'Ever used synthetic marijuana',
       'Tried marijuana for the first time before age 13 years',
       'Ever used methamphetamines', 'Ever injected any illegal drug',
       'Ever used ecstasy',
       'Reported 10 or more as the largest number of drinks they had in a row',
       'Usually got the alcohol they drank by someone giving it to them',
       "Ever took prescription pain medicine without a doctor's prescription or differently than how a doctor told them to use it",
       'Ever used hallucinogenic drugs',
       'Reported current binge drinking'], dtype=object)

In [8]:
for i in Greater_Risk_Question:
    print(len(df.loc[df.Greater_Risk_Question == i, 'Description'].unique()))
    print(i)
    print(df.loc[df.Greater_Risk_Question == i, 'Description'].unique())

1
Ever used cocaine
['any form of cocaine, such as powder, crack, or freebase, one or more times during their life']
1
Currently drank alcohol
['at least one drink of alcohol, on at least 1 day during the 30 days before the survey']
1
Had their first drink of alcohol before age 13 years
['other than a few sips']
1
Ever took steroids without a doctor's prescription
['pills or shots, one or more times during their life']
1
Ever used inhalants
['sniffed glue, breathed the contents of aerosol spray cans, or inhaled any paints or sprays to get high, one or more times during their life']
1
Were offered, sold, or given an illegal drug on school property
['during the 12 months before the survey']
1
Ever used marijuana
['also called grass, pot, or weed, one or more times during their life']
1
Ever used heroin
['also called "smack," "junk," or "China White," one or more times during their life']
1
Ever drank alcohol
['at least one drink of alcohol, on at least 1 day during their life']
1
Currently used marijuana
['also called grass, pot, or weed, one or more times during the 30 days before the survey']
1
Ever used synthetic marijuana
['also called "K2," "Spice," "fake weed," "King Kong," "Yucatan Fire," "Skunk," or "Moon Rocks," one or more times during their life']
1
Tried marijuana for the first time before age 13 years
['also called grass, pot, or weed']
1
Ever used methamphetamines
['also called "speed," "crystal," "crank," or "ice," one or more times during their life']
1
Ever injected any illegal drug
['used a needle to inject any illegal drug into their body, one or more times during their life']
1
Ever used ecstasy
['also called "MDMA," one or more times during their life']
1
Reported 10 or more as the largest number of drinks they had in a row
['within a couple of hours, during the 30 days before the survey']
1
Usually got the alcohol they drank by someone giving it to them
['during the 30 days before the survey, among students who currently drank alcohol']
1
Ever took prescription pain medicine without a doctor's prescription or differently than how a doctor told them to use it
['counting drugs such as codeine, Vicodin, Oxycontin, Hydrocodone, and Percocet, one or more times during their life']
1
Ever used hallucinogenic drugs
['such as LSD, acid, PCP, angel dust, mescaline, or mushrooms, one or more times during their life']
1
Reported current binge drinking
['four or more drinks of alcohol in a row (if they were female) or five or more drinks of alcohol in a row (if they were male), within a couple of hours, on at least 1 day during the 30 days before the survey']

In [9]:
df.drop(columns=['Description'], inplace=True)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55399 entries, 0 to 55398
Data columns (total 15 columns):
Patient_ID                  55399 non-null int64
YEAR                        55399 non-null int64
LocationDesc                55399 non-null object
Subtopic                    55399 non-null int64
Greater_Risk_Question       55399 non-null object
Sample_Size                 55399 non-null float64
Sex                         55399 non-null object
Race                        55399 non-null object
Grade                       55399 non-null int64
QuestionCode                55399 non-null object
StratID1                    55399 non-null int64
StratID2                    55399 non-null int64
StratID3                    55399 non-null int64
StratificationType          55399 non-null object
Greater_Risk_Probability    55399 non-null float64
dtypes: float64(2), int64(7), object(6)
memory usage: 6.3+ MB

In [11]:
### label encoding
### LocationDesc, Greater_Risk_Question, Sex, Race, QuestionCode, StratificationType
df_encoded = df.copy()

from sklearn.preprocessing import LabelEncoder
encoders = {}
for clm in ['LocationDesc', 'Greater_Risk_Question', 'Sex', 'Race', 'QuestionCode', 'StratificationType']:
    le = LabelEncoder()
    df_encoded[clm] = le.fit_transform(df_encoded[clm])
    encoders[clm] = le
df_encoded.head()

,Patient_ID,YEAR,LocationDesc,Subtopic,Greater_Risk_Question,Sample_Size,Sex,Race,Grade,QuestionCode,StratID1,StratID2,StratID3,StratificationType,Greater_Risk_Probability
0,1,1995,32,1,6,335.0,0,3,4,9,1,4,0,0,7.4793
1,2,1997,32,0,0,382.0,2,2,4,2,0,3,0,0,49.6852
2,3,1993,54,0,14,196.0,0,7,0,1,1,6,2,3,47.8132
3,4,2017,71,1,6,104.0,1,1,4,9,2,2,0,3,3.4554
4,5,2007,77,1,5,100.0,0,4,4,15,1,7,0,0,0.0000

In [12]:
from sklearn.preprocessing import MinMaxScaler
df_scaled = df_encoded.copy()
scaler = {}
for clm in ['YEAR', 'LocationDesc', 'Subtopic', 'Greater_Risk_Question', 'Sample_Size', 'Sex', 'Race', 
            'Grade', 'QuestionCode', 'StratID1', 'StratID2', 'StratID3', 'StratificationType']:
    sc = MinMaxScaler()
    df_scaled[clm] = sc.fit_transform(df_scaled[clm].values.reshape(-1, 1))
    scaler[clm] = sc

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)

In [13]:
df_scaled.head()

,Patient_ID,YEAR,LocationDesc,Subtopic,Greater_Risk_Question,Sample_Size,Sex,Race,Grade,QuestionCode,StratID1,StratID2,StratID3,StratificationType,Greater_Risk_Probability
0,1,0.153846,0.355556,1.0,0.315789,0.005316,0.0,0.428571,1.0,0.473684,0.5,0.571429,0.0,0.00,7.4793
1,2,0.230769,0.355556,0.0,0.000000,0.006192,1.0,0.285714,1.0,0.105263,0.0,0.428571,0.0,0.00,49.6852
2,3,0.076923,0.600000,0.0,0.736842,0.002723,0.0,1.000000,0.0,0.052632,0.5,0.857143,0.5,0.75,47.8132
3,4,1.000000,0.788889,1.0,0.315789,0.001007,0.5,0.142857,1.0,0.473684,1.0,0.285714,0.0,0.75,3.4554
4,5,0.615385,0.855556,1.0,0.263158,0.000933,0.0,0.571429,1.0,0.789474,0.5,1.000000,0.0,0.00,0.0000

In [14]:
X = df_scaled[['YEAR', 'LocationDesc', 'Subtopic', 'Greater_Risk_Question', 'Sample_Size', 'Sex', 'Race', 
            'Grade', 'QuestionCode', 'StratID1', 'StratID2', 'StratID3', 'StratificationType']]
Y = df_scaled[['Greater_Risk_Probability']]

In [15]:
X.head()

,YEAR,LocationDesc,Subtopic,Greater_Risk_Question,Sample_Size,Sex,Race,Grade,QuestionCode,StratID1,StratID2,StratID3,StratificationType
0,0.153846,0.355556,1.0,0.315789,0.005316,0.0,0.428571,1.0,0.473684,0.5,0.571429,0.0,0.00
1,0.230769,0.355556,0.0,0.000000,0.006192,1.0,0.285714,1.0,0.105263,0.0,0.428571,0.0,0.00
2,0.076923,0.600000,0.0,0.736842,0.002723,0.0,1.000000,0.0,0.052632,0.5,0.857143,0.5,0.75
3,1.000000,0.788889,1.0,0.315789,0.001007,0.5,0.142857,1.0,0.473684,1.0,0.285714,0.0,0.75
4,0.615385,0.855556,1.0,0.263158,0.000933,0.0,0.571429,1.0,0.789474,0.5,1.000000,0.0,0.00

In [16]:
Y.head()

   Greater_Risk_Probability
0                    7.4793
1                   49.6852
2                   47.8132
3                    3.4554
4                    0.0000

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.20, random_state=42)

In [18]:
from sklearn.neural_network import MLPRegressor
nn1 = MLPRegressor(hidden_layer_sizes=(15,30,30,15,), verbose=True, max_iter=1500)
nn1

MLPRegressor(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(15, 30, 30, 15), learning_rate='constant',
       learning_rate_init=0.001, max_iter=1500, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=True, warm_start=False)

In [19]:
# nn1.fit(X=X_train, y=y_train)
nn1.fit(X=X, y=Y)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:1316: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Iteration 1, loss = 233.80328342
Iteration 2, loss = 93.40212902
Iteration 3, loss = 63.92261412
Iteration 4, loss = 46.76036008
Iteration 5, loss = 38.60072309
Iteration 6, loss = 35.51272357
Iteration 7, loss = 33.69498105
Iteration 8, loss = 32.32787386
Iteration 9, loss = 31.03985140
Iteration 10, loss = 30.27337739
Iteration 11, loss = 29.50754473
Iteration 12, loss = 28.71528779
Iteration 13, loss = 28.01603803
Iteration 14, loss = 27.58029121
Iteration 15, loss = 27.40595088
Iteration 16, loss = 26.89800082
Iteration 17, loss = 26.71696768
Iteration 18, loss = 26.36221235
Iteration 19, loss = 26.18758884
Iteration 20, loss = 25.97827394
Iteration 21, loss = 25.73534477
Iteration 22, loss = 25.65140219
Iteration 23, loss = 25.36126064
Iteration 24, loss = 25.20345132
Iteration 25, loss = 25.25774925
Iteration 26, loss = 24.97112528
Iteration 27, loss = 25.00023800
Iteration 28, loss = 24.66031784
Iteration 29, loss = 24.36930572
Iteration 30, loss = 24.62649146
Iteration 31, loss = 24.46483274
Iteration 32, loss = 24.40978427
Iteration 33, loss = 24.00801582
Iteration 34, loss = 24.03645622
Iteration 35, loss = 23.93191013
Iteration 36, loss = 23.84295686
Iteration 37, loss = 23.85750428
Iteration 38, loss = 23.68670735
Iteration 39, loss = 23.59317291
Iteration 40, loss = 23.57168599
Iteration 41, loss = 23.38554696
Iteration 42, loss = 23.27164225
Iteration 43, loss = 23.25963310
Iteration 44, loss = 23.37013368
Iteration 45, loss = 23.11636258
Iteration 46, loss = 23.06035713
Iteration 47, loss = 23.06254008
Iteration 48, loss = 23.10243246
Iteration 49, loss = 22.94058730
Iteration 50, loss = 22.91084132
Iteration 51, loss = 22.72667462
Iteration 52, loss = 22.64106227
Iteration 53, loss = 22.68943360
Iteration 54, loss = 22.70495585
Iteration 55, loss = 22.50349242
Iteration 56, loss = 22.60751032
Iteration 57, loss = 22.61737493
Iteration 58, loss = 22.48284215
Iteration 59, loss = 22.41908087
Iteration 60, loss = 22.50853309
Iteration 61, loss = 22.21736402
Iteration 62, loss = 22.26643837
Iteration 63, loss = 22.24779051
Iteration 64, loss = 22.29860179
Iteration 65, loss = 22.13776772
Iteration 66, loss = 22.21730146
Iteration 67, loss = 21.99789121
Iteration 68, loss = 22.04847892
Iteration 69, loss = 22.19836306
Iteration 70, loss = 21.98294514
Iteration 71, loss = 21.97430891
Iteration 72, loss = 22.07286504
Iteration 73, loss = 21.87510967
Iteration 74, loss = 21.88569731
Iteration 75, loss = 21.92911650
Iteration 76, loss = 21.75682488
Iteration 77, loss = 21.73267462
Iteration 78, loss = 21.62171748
Iteration 79, loss = 21.77087621
Iteration 80, loss = 21.72609078
Iteration 81, loss = 21.71925521
Iteration 82, loss = 21.67635650
Iteration 83, loss = 21.63531197
Iteration 84, loss = 21.53147579
Iteration 85, loss = 21.54063970
Iteration 86, loss = 21.64788190
Iteration 87, loss = 21.57466141
Iteration 88, loss = 21.53534949
Iteration 89, loss = 21.47362777
Iteration 90, loss = 21.46832676
Iteration 91, loss = 21.45508533
Iteration 92, loss = 21.38243151
Iteration 93, loss = 21.27791181
Iteration 94, loss = 21.37961185
Iteration 95, loss = 21.34517644
Iteration 96, loss = 21.32300355
Iteration 97, loss = 21.19215352
Iteration 98, loss = 21.32188733
Iteration 99, loss = 21.24385911
Iteration 100, loss = 21.19806222
Iteration 101, loss = 21.21830469
Iteration 102, loss = 21.11103362
Iteration 103, loss = 21.20227993
Iteration 104, loss = 21.05147122
Iteration 105, loss = 20.98676850
Iteration 106, loss = 21.15508621
Iteration 107, loss = 21.00222164
Iteration 108, loss = 20.98679876
Iteration 109, loss = 21.09383371
Iteration 110, loss = 21.04914342
Iteration 111, loss = 20.95526983
Iteration 112, loss = 20.98649112
Iteration 113, loss = 20.82368577
Iteration 114, loss = 20.97933808
Iteration 115, loss = 20.91245738
Iteration 116, loss = 20.87331352
Iteration 117, loss = 20.83955829
Iteration 118, loss = 20.84493487
Iteration 119, loss = 20.72274813
Iteration 120, loss = 20.67047586
Iteration 121, loss = 20.70391965
Iteration 122, loss = 20.67315005
Iteration 123, loss = 20.61481904
Iteration 124, loss = 20.69604531
Iteration 125, loss = 20.60315143
Iteration 126, loss = 20.55789071
Iteration 127, loss = 20.57482486
Iteration 128, loss = 20.54000829
Iteration 129, loss = 20.53989749
Iteration 130, loss = 20.51129830
Iteration 131, loss = 20.46627557
Iteration 132, loss = 20.43327058
Iteration 133, loss = 20.39054618
Iteration 134, loss = 20.51244856
Iteration 135, loss = 20.45246207
Iteration 136, loss = 20.31299995
Iteration 137, loss = 20.41574669
Iteration 138, loss = 20.23999421
Iteration 139, loss = 20.34594454
Iteration 140, loss = 20.20313655
Iteration 141, loss = 20.31311122
Iteration 142, loss = 20.12411835
Iteration 143, loss = 20.10400917
Iteration 144, loss = 20.21986144
Iteration 145, loss = 20.14269557
Iteration 146, loss = 20.04893071
Iteration 147, loss = 20.07749302
Iteration 148, loss = 19.92966869
Iteration 149, loss = 20.01225366
Iteration 150, loss = 19.99844128
Iteration 151, loss = 19.91133231
Iteration 152, loss = 19.85092049
Iteration 153, loss = 19.89816183
Iteration 154, loss = 19.88305608
Iteration 155, loss = 19.84219883
Iteration 156, loss = 19.78185451
Iteration 157, loss = 19.71089834
Iteration 158, loss = 19.78632743
Iteration 159, loss = 19.70583839
Iteration 160, loss = 19.70296930
Iteration 161, loss = 19.62890900
Iteration 162, loss = 19.62249639
Iteration 163, loss = 19.65055425
Iteration 164, loss = 19.56060192
Iteration 165, loss = 19.76464667
Iteration 166, loss = 19.63908863
Iteration 167, loss = 19.50023554
Iteration 168, loss = 19.44473256
Iteration 169, loss = 19.54523648
Iteration 170, loss = 19.47606141
Iteration 171, loss = 19.50245718
Iteration 172, loss = 19.55415627
Iteration 173, loss = 19.39474621
Iteration 174, loss = 19.27918710
Iteration 175, loss = 19.43073564
Iteration 176, loss = 19.30974287
Iteration 177, loss = 19.31967131
Iteration 178, loss = 19.25860325
Iteration 179, loss = 19.30552286
Iteration 180, loss = 19.20657517
Iteration 181, loss = 19.23316968
Iteration 182, loss = 19.31080961
Iteration 183, loss = 19.21085677
Iteration 184, loss = 19.10887002
Iteration 185, loss = 19.24184007
Iteration 186, loss = 19.20837835
Iteration 187, loss = 19.09469687
Iteration 188, loss = 19.11152623
Iteration 189, loss = 19.17283947
Iteration 190, loss = 18.98427658
Iteration 191, loss = 19.09097732
Iteration 192, loss = 19.05518310
Iteration 193, loss = 18.98308534
Iteration 194, loss = 18.97209562
Iteration 195, loss = 19.02733356
Iteration 196, loss = 19.01013287
Iteration 197, loss = 18.91436476
Iteration 198, loss = 18.87547711
Iteration 199, loss = 18.83301519
Iteration 200, loss = 18.94334478
Iteration 201, loss = 18.87143662
Iteration 202, loss = 18.95936245
Iteration 203, loss = 18.91537721
Iteration 204, loss = 18.78370734
Iteration 205, loss = 18.93139983
Iteration 206, loss = 18.92705933
Iteration 207, loss = 18.85383825
Iteration 208, loss = 18.71951682
Iteration 209, loss = 18.84420176
Iteration 210, loss = 18.80980396
Iteration 211, loss = 18.64991005
Iteration 212, loss = 18.74694955
Iteration 213, loss = 18.68230803
Iteration 214, loss = 18.68912060
Iteration 215, loss = 18.84752847
Iteration 216, loss = 18.76173340
Iteration 217, loss = 18.74371108
Iteration 218, loss = 18.61695606
Iteration 219, loss = 18.59904326
Iteration 220, loss = 18.72310127
Iteration 221, loss = 18.54533664
Iteration 222, loss = 18.57262659
Iteration 223, loss = 18.61226024
Iteration 224, loss = 18.52774722
Iteration 225, loss = 18.79014381
Iteration 226, loss = 18.65068275
Iteration 227, loss = 18.62709283
Iteration 228, loss = 18.55300144
Iteration 229, loss = 18.44979367
Iteration 230, loss = 18.63406728
Iteration 231, loss = 18.50670252
Iteration 232, loss = 18.37567439
Iteration 233, loss = 18.37659472
Iteration 234, loss = 18.37255948
Iteration 235, loss = 18.37596558
Iteration 236, loss = 18.45714634
Iteration 237, loss = 18.55273278
Iteration 238, loss = 18.32717577
Iteration 239, loss = 18.40083535
Iteration 240, loss = 18.41446719
Iteration 241, loss = 18.38646791
Iteration 242, loss = 18.36213563
Iteration 243, loss = 18.42865371
Iteration 244, loss = 18.27582318
Iteration 245, loss = 18.45079436

Iteration 246, loss = 18.19700477
Iteration 247, loss = 18.21347222
Iteration 248, loss = 18.43136466
Iteration 249, loss = 18.16080399
Iteration 250, loss = 18.30445745
Iteration 251, loss = 18.27261258
Iteration 252, loss = 18.43996733
Iteration 253, loss = 18.25482034
Iteration 254, loss = 18.12597126
Iteration 255, loss = 18.12779063
Iteration 256, loss = 18.30464980
Iteration 257, loss = 18.18282195
Iteration 258, loss = 18.13744930
Iteration 259, loss = 18.12030292
Iteration 260, loss = 18.14435115
Iteration 261, loss = 17.91364532
Iteration 262, loss = 17.99292522
Iteration 263, loss = 17.98260628
Iteration 264, loss = 18.07543901
Iteration 265, loss = 17.89754085
Iteration 266, loss = 17.91331861
Iteration 267, loss = 17.98990856
Iteration 268, loss = 18.09131388
Iteration 269, loss = 18.06070993
Iteration 270, loss = 17.94719326
Iteration 271, loss = 18.08135321
Iteration 272, loss = 18.03430851
Iteration 273, loss = 17.88244364
Iteration 274, loss = 17.86961995
Iteration 275, loss = 17.79523071
Iteration 276, loss = 17.92613830
Iteration 277, loss = 17.86566454
Iteration 278, loss = 17.81728936
Iteration 279, loss = 17.82712630
Iteration 280, loss = 17.78683305
Iteration 281, loss = 17.84447747
Iteration 282, loss = 17.96458805
Iteration 283, loss = 17.84865798
Iteration 284, loss = 17.93609383
Iteration 285, loss = 17.81990936
Iteration 286, loss = 17.78520672
Iteration 287, loss = 17.85944105
Iteration 288, loss = 17.72551058
Iteration 289, loss = 17.74759747
Iteration 290, loss = 17.86538554
Iteration 291, loss = 17.70543328
Iteration 292, loss = 17.76156437
Iteration 293, loss = 17.65032597
Iteration 294, loss = 17.73133820
Iteration 295, loss = 17.69957303
Iteration 296, loss = 17.66259032
Iteration 297, loss = 17.68341135
Iteration 298, loss = 17.75737755
Iteration 299, loss = 17.68883906
Iteration 300, loss = 17.63216923
Iteration 301, loss = 17.65872004
Iteration 302, loss = 17.61478042
Iteration 303, loss = 17.66200873
Iteration 304, loss = 17.66792086
Iteration 305, loss = 17.53775197
Iteration 306, loss = 17.62360022
Iteration 307, loss = 17.61720617
Iteration 308, loss = 17.61320607
Iteration 309, loss = 17.60028609
Iteration 310, loss = 17.59785079
Iteration 311, loss = 17.63068021
Iteration 312, loss = 17.58231012
Iteration 313, loss = 17.65083605
Iteration 314, loss = 17.72653909
Iteration 315, loss = 17.52980819
Iteration 316, loss = 17.50552949
Iteration 317, loss = 17.45967059
Iteration 318, loss = 17.65078105
Iteration 319, loss = 17.50916725
Iteration 320, loss = 17.75645465
Iteration 321, loss = 17.48088144
Iteration 322, loss = 17.47586431
Iteration 323, loss = 17.56961094
Iteration 324, loss = 17.52182997
Iteration 325, loss = 17.44116124
Iteration 326, loss = 17.53791975
Iteration 327, loss = 17.51021631
Iteration 328, loss = 17.49142368
Iteration 329, loss = 17.54696040
Iteration 330, loss = 17.48901668
Iteration 331, loss = 17.53417005
Iteration 332, loss = 17.48902507
Iteration 333, loss = 17.42743229
Iteration 334, loss = 17.38497572
Iteration 335, loss = 17.42610868
Iteration 336, loss = 17.47472927
Iteration 337, loss = 17.42038635
Iteration 338, loss = 17.50233625
Iteration 339, loss = 17.36099275
Iteration 340, loss = 17.44368172
Iteration 341, loss = 17.39505306
Iteration 342, loss = 17.43059316
Iteration 343, loss = 17.53529157
Iteration 344, loss = 17.42866575
Iteration 345, loss = 17.45767876
Iteration 346, loss = 17.41511988
Iteration 347, loss = 17.39920829
Iteration 348, loss = 17.44391713
Iteration 349, loss = 17.37537366
Iteration 350, loss = 17.25601599
Iteration 351, loss = 17.39968997
Iteration 352, loss = 17.38571214
Iteration 353, loss = 17.57213674
Iteration 354, loss = 17.31979261
Iteration 355, loss = 17.33292626
Iteration 356, loss = 17.27567802
Iteration 357, loss = 17.31507873
Iteration 358, loss = 17.26199317
Iteration 359, loss = 17.32887400
Iteration 360, loss = 17.36427941
Iteration 361, loss = 17.18424617
Iteration 362, loss = 17.26991906
Iteration 363, loss = 17.27485259
Iteration 364, loss = 17.32167906
Iteration 365, loss = 17.32101681
Iteration 366, loss = 17.29848689
Iteration 367, loss = 17.41283210
Iteration 368, loss = 17.22359547
Iteration 369, loss = 17.17749342
Iteration 370, loss = 17.17889661
Iteration 371, loss = 17.30619374
Iteration 372, loss = 17.15445124
Iteration 373, loss = 17.25844236
Iteration 374, loss = 17.19647675
Iteration 375, loss = 17.24665379
Iteration 376, loss = 17.23665564
Iteration 377, loss = 17.24347514
Iteration 378, loss = 17.34119044
Iteration 379, loss = 17.16208705
Iteration 380, loss = 17.17441741
Iteration 381, loss = 17.28076254
Iteration 382, loss = 17.21320926
Iteration 383, loss = 17.13819124
Iteration 384, loss = 17.15422818
Iteration 385, loss = 17.18583133
Iteration 386, loss = 17.17453880
Iteration 387, loss = 17.25625333
Iteration 388, loss = 17.15108440
Iteration 389, loss = 17.13241635
Iteration 390, loss = 17.25406537
Iteration 391, loss = 17.14417389
Iteration 392, loss = 17.18293181
Iteration 393, loss = 17.19556355
Iteration 394, loss = 17.12934538
Iteration 395, loss = 17.14925586
Iteration 396, loss = 17.16369330
Iteration 397, loss = 17.09761679
Iteration 398, loss = 17.17766791
Iteration 399, loss = 17.05745312
Iteration 400, loss = 17.12248221
Iteration 401, loss = 17.30913926
Iteration 402, loss = 17.03769522
Iteration 403, loss = 17.07417540
Iteration 404, loss = 17.08482825
Iteration 405, loss = 17.07014113
Iteration 406, loss = 17.14580830
Iteration 407, loss = 17.05642965
Iteration 408, loss = 16.99649528
Iteration 409, loss = 17.21544509
Iteration 410, loss = 17.15461568
Iteration 411, loss = 16.96989681
Iteration 412, loss = 17.05426647
Iteration 413, loss = 17.11354385
Iteration 414, loss = 17.15494559
Iteration 415, loss = 17.12149146
Iteration 416, loss = 17.26977110
Iteration 417, loss = 17.01739436
Iteration 418, loss = 17.12988899
Iteration 419, loss = 17.02729371
Iteration 420, loss = 16.93674219
Iteration 421, loss = 17.14372630
Iteration 422, loss = 16.99618318
Iteration 423, loss = 16.93939717
Iteration 424, loss = 17.03823951
Iteration 425, loss = 17.04455475
Iteration 426, loss = 17.03572002
Iteration 427, loss = 17.01507466
Iteration 428, loss = 17.06681240
Iteration 429, loss = 17.05546697
Iteration 430, loss = 16.99817991
Iteration 431, loss = 16.96649380
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.

MLPRegressor(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(15, 30, 30, 15), learning_rate='constant',
       learning_rate_init=0.001, max_iter=1500, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=True, warm_start=False)

In [20]:
print('train:', nn1.score(X, Y))
print('train:', nn1.score(X_train, y_train))
print('test:', nn1.score(X_test, y_test))

train: 0.9201911945852497
train: 0.9200612348926847
test: 0.9207178604756143

In [21]:
test = pd.read_csv('test_file.csv')

In [22]:
test.head()

,Patient_ID,YEAR,LocationDesc,Subtopic,Greater_Risk_Question,Description,Sample_Size,Sex,Race,Grade,GeoLocation,QuestionCode,StratID1,StratID2,StratID3,StratificationType
0,55400,2007,Navajo,1,Ever used marijuana,"also called grass, pot, or weed, one or more t...",157.0,Male,Hispanic or Latino,3,NaN,H46,2,4,1,Other
1,55401,2001,Florida,1,Currently used marijuana,"also called grass, pot, or weed, one or more t...",724.0,Total,Total,2,"(28.932040377000476, -81.92896053899966)",H48,0,0,4,State
2,55402,2005,"Charlotte-Mecklenburg County, NC",1,"Were offered, sold, or given an illegal drug o...",during the 12 months before the survey,105.0,Male,Hispanic or Latino,4,"(35.227087, -80.843127)",H58,2,4,0,Local
3,55403,2017,Nevada,1,Ever used synthetic marijuana,"also called ""K2,"" ""Spice,"" ""fake weed,"" ""King ...",157.0,Male,Total,2,"(39.493240390000494, -117.07184056399967)",H54,2,0,4,State
4,55404,2007,Illinois,1,Ever used heroin,"also called ""smack,"" ""junk,"" or ""China White,""...",174.0,Total,Black or African American,1,"(40.48501028300046, -88.99771017799969)",H51,0,3,3,State

In [23]:
test.drop(columns=['GeoLocation'], inplace=True)
test.drop(columns=['Description'], inplace=True)

In [24]:
for clm in ['LocationDesc', 'Greater_Risk_Question', 'Sex', 'Race', 'QuestionCode', 'StratificationType']:
    test[clm] = encoders[clm].transform(test[clm])
test.head()

,Patient_ID,YEAR,LocationDesc,Subtopic,Greater_Risk_Question,Sample_Size,Sex,Race,Grade,QuestionCode,StratID1,StratID2,StratID3,StratificationType
0,55400,2007,52,1,11,157.0,1,3,3,6,2,4,1,2
1,55401,2001,27,1,1,724.0,2,6,2,8,0,0,4,3
2,55402,2005,14,1,19,105.0,1,3,4,18,2,4,0,0
3,55403,2017,54,1,13,157.0,1,6,2,14,2,0,4,3
4,55404,2007,34,1,9,174.0,2,2,1,11,0,3,3,3

In [25]:
for clm in ['YEAR', 'LocationDesc', 'Subtopic', 'Greater_Risk_Question', 'Sample_Size', 'Sex', 'Race', 
            'Grade', 'QuestionCode', 'StratID1', 'StratID2', 'StratID3', 'StratificationType']:
    test[clm] = scaler[clm].transform(test[clm].values.reshape(-1, 1))
test.head()

,Patient_ID,YEAR,LocationDesc,Subtopic,Greater_Risk_Question,Sample_Size,Sex,Race,Grade,QuestionCode,StratID1,StratID2,StratID3,StratificationType
0,55400,0.615385,0.577778,1.0,0.578947,0.001996,0.5,0.428571,0.75,0.315789,1.0,0.571429,0.25,0.50
1,55401,0.384615,0.300000,1.0,0.052632,0.012571,1.0,0.857143,0.50,0.421053,0.0,0.000000,1.00,0.75
2,55402,0.538462,0.155556,1.0,1.000000,0.001026,0.5,0.428571,1.00,0.947368,1.0,0.571429,0.00,0.00
3,55403,1.000000,0.600000,1.0,0.684211,0.001996,0.5,0.857143,0.50,0.736842,1.0,0.000000,1.00,0.75
4,55404,0.615385,0.377778,1.0,0.473684,0.002313,1.0,0.285714,0.25,0.578947,0.0,0.428571,0.75,0.75

In [26]:
prediction = pd.DataFrame()
prediction['Patient_ID'] = test['Patient_ID']
prediction['Greater_Risk_Probability'] = nn1.predict(test[['YEAR', 'LocationDesc', 'Subtopic', 'Greater_Risk_Question', 
                                                           'Sample_Size', 'Sex', 'Race', 'Grade', 'QuestionCode', 
                                                           'StratID1', 'StratID2', 'StratID3', 'StratificationType']])

In [27]:
prediction.to_csv('sample_submission.csv', index=False)
prediction.head()

   Patient_ID  Greater_Risk_Probability
0       55400                 47.406598
1       55401                 31.386098
2       55402                 44.636021
3       55403                 20.532971
4       55404                  8.326856