In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('train_file.csv')

In [3]:
df.head()

,Patient_ID,YEAR,LocationDesc,Subtopic,Greater_Risk_Question,Description,Sample_Size,Sex,Race,Grade,GeoLocation,QuestionCode,StratID1,StratID2,StratID3,StratificationType,Greater_Risk_Probability
0,1,1995,"Houston, TX",1,Ever used cocaine,"any form of cocaine, such as powder, crack, or...",335.0,Female,Hispanic or Latino,4,"(29.760427, -95.369803)",H49,1,4,0,Local,7.4793
1,2,1997,"Houston, TX",0,Currently drank alcohol,"at least one drink of alcohol, on at least 1 d...",382.0,Total,Black or African American,4,"(29.760427, -95.369803)",H42,0,3,0,Local,49.6852
2,3,1993,Nevada,0,Had their first drink of alcohol before age 13...,other than a few sips,196.0,Female,White,0,"(39.493240390000494, -117.07184056399967)",H41,1,6,2,State,47.8132
3,4,2017,Pennsylvania,1,Ever used cocaine,"any form of cocaine, such as powder, crack, or...",104.0,Male,Asian,4,"(40.79373015200048, -77.86070029399963)",H49,2,2,0,State,3.4554
4,5,2007,"San Francisco, CA",1,Ever took steroids without a doctor's prescrip...,"pills or shots, one or more times during their...",100.0,Female,Multiple Race,4,"(37.77493, -122.419416)",H55,1,7,0,Local,0.0000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55399 entries, 0 to 55398
Data columns (total 17 columns):
Patient_ID                  55399 non-null int64
YEAR                        55399 non-null int64
LocationDesc                55399 non-null object
Subtopic                    55399 non-null int64
Greater_Risk_Question       55399 non-null object
Description                 55399 non-null object
Sample_Size                 55399 non-null float64
Sex                         55399 non-null object
Race                        55399 non-null object
Grade                       55399 non-null int64
GeoLocation                 52098 non-null object
QuestionCode                55399 non-null object
StratID1                    55399 non-null int64
StratID2                    55399 non-null int64
StratID3                    55399 non-null int64
StratificationType          55399 non-null object
Greater_Risk_Probability    55399 non-null float64
dtypes: float64(2), int64(7), object(8)
memory usage: 7.2+ MB

In [5]:
df.drop(columns=['GeoLocation'], inplace=True)

In [8]:
df.describe(include='all')

,Patient_ID,YEAR,LocationDesc,Subtopic,Greater_Risk_Question,Description,Sample_Size,Sex,Race,Grade,QuestionCode,StratID1,StratID2,StratID3,StratificationType,Greater_Risk_Probability
count,55399.000000,55399.000000,55399,55399.000000,55399,55399,55399.000000,55399,55399,55399.000000,55399,55399.000000,55399.000000,55399.000000,55399,55399.000000
unique,NaN,NaN,91,NaN,20,20,NaN,3,8,NaN,20,NaN,NaN,NaN,5,NaN
top,NaN,NaN,United States,NaN,Currently used marijuana,"also called grass, pot, or weed, one or more t...",NaN,Total,Total,NaN,H48,NaN,NaN,NaN,State,NaN
freq,NaN,NaN,2276,NaN,4421,4421,NaN,22057,22252,NaN,4421,NaN,NaN,NaN,31878,NaN
mean,27700.000000,2007.674308,NaN,0.747270,NaN,NaN,566.206339,NaN,NaN,2.238488,NaN,0.897327,2.718479,1.708695,NaN,24.365664
std,15992.458118,6.906621,NaN,0.434581,NaN,NaN,1148.727489,NaN,NaN,1.494005,NaN,0.826494,2.516150,1.448596,NaN,20.492551
min,1.000000,1991.000000,NaN,0.000000,NaN,NaN,50.000000,NaN,NaN,0.000000,NaN,0.000000,0.000000,0.000000,NaN,0.000000
25%,13850.500000,2003.000000,NaN,0.000000,NaN,NaN,165.000000,NaN,NaN,1.000000,NaN,0.000000,0.000000,0.000000,NaN,8.280050
50%,27700.000000,2009.000000,NaN,1.000000,NaN,NaN,275.000000,NaN,NaN,2.000000,NaN,1.000000,3.000000,2.000000,NaN,17.555600
75%,41549.500000,2013.000000,NaN,1.000000,NaN,NaN,560.500000,NaN,NaN,4.000000,NaN,2.000000,6.000000,3.000000,NaN,35.430750
max,55399.000000,2017.000000,NaN,1.000000,NaN,NaN,53664.000000,NaN,NaN,4.000000,NaN,2.000000,7.000000,4.000000,NaN,99.449400

In [18]:
Greater_Risk_Question = df.Greater_Risk_Question.unique()
Greater_Risk_Question

array(['Ever used cocaine', 'Currently drank alcohol',
       'Had their first drink of alcohol before age 13 years',
       "Ever took steroids without a doctor's prescription",
       'Ever used inhalants',
       'Were offered, sold, or given an illegal drug on school property',
       'Ever used marijuana', 'Ever used heroin', 'Ever drank alcohol',
       'Currently used marijuana', 'Ever used synthetic marijuana',
       'Tried marijuana for the first time before age 13 years',
       'Ever used methamphetamines', 'Ever injected any illegal drug',
       'Ever used ecstasy',
       'Reported 10 or more as the largest number of drinks they had in a row',
       'Usually got the alcohol they drank by someone giving it to them',
       "Ever took prescription pain medicine without a doctor's prescription or differently than how a doctor told them to use it",
       'Ever used hallucinogenic drugs',
       'Reported current binge drinking'], dtype=object)

In [21]:
for i in Greater_Risk_Question:
    print(len(df.loc[df.Greater_Risk_Question == i, 'Description'].unique()))
    print(i)
    print(df.loc[df.Greater_Risk_Question == i, 'Description'].unique())

1
Ever used cocaine
['any form of cocaine, such as powder, crack, or freebase, one or more times during their life']
1
Currently drank alcohol
['at least one drink of alcohol, on at least 1 day during the 30 days before the survey']
1
Had their first drink of alcohol before age 13 years
['other than a few sips']
1
Ever took steroids without a doctor's prescription
['pills or shots, one or more times during their life']
1
Ever used inhalants
['sniffed glue, breathed the contents of aerosol spray cans, or inhaled any paints or sprays to get high, one or more times during their life']
1
Were offered, sold, or given an illegal drug on school property
['during the 12 months before the survey']
1
Ever used marijuana
['also called grass, pot, or weed, one or more times during their life']
1
Ever used heroin
['also called "smack," "junk," or "China White," one or more times during their life']
1
Ever drank alcohol
['at least one drink of alcohol, on at least 1 day during their life']
1
Currently used marijuana
['also called grass, pot, or weed, one or more times during the 30 days before the survey']
1
Ever used synthetic marijuana
['also called "K2," "Spice," "fake weed," "King Kong," "Yucatan Fire," "Skunk," or "Moon Rocks," one or more times during their life']
1
Tried marijuana for the first time before age 13 years
['also called grass, pot, or weed']
1
Ever used methamphetamines
['also called "speed," "crystal," "crank," or "ice," one or more times during their life']
1
Ever injected any illegal drug
['used a needle to inject any illegal drug into their body, one or more times during their life']
1
Ever used ecstasy
['also called "MDMA," one or more times during their life']
1
Reported 10 or more as the largest number of drinks they had in a row
['within a couple of hours, during the 30 days before the survey']
1
Usually got the alcohol they drank by someone giving it to them
['during the 30 days before the survey, among students who currently drank alcohol']
1
Ever took prescription pain medicine without a doctor's prescription or differently than how a doctor told them to use it
['counting drugs such as codeine, Vicodin, Oxycontin, Hydrocodone, and Percocet, one or more times during their life']
1
Ever used hallucinogenic drugs
['such as LSD, acid, PCP, angel dust, mescaline, or mushrooms, one or more times during their life']
1
Reported current binge drinking
['four or more drinks of alcohol in a row (if they were female) or five or more drinks of alcohol in a row (if they were male), within a couple of hours, on at least 1 day during the 30 days before the survey']

In [23]:
df.drop(columns=['Description'], inplace=True)

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55399 entries, 0 to 55398
Data columns (total 15 columns):
Patient_ID                  55399 non-null int64
YEAR                        55399 non-null int64
LocationDesc                55399 non-null object
Subtopic                    55399 non-null int64
Greater_Risk_Question       55399 non-null object
Sample_Size                 55399 non-null float64
Sex                         55399 non-null object
Race                        55399 non-null object
Grade                       55399 non-null int64
QuestionCode                55399 non-null object
StratID1                    55399 non-null int64
StratID2                    55399 non-null int64
StratID3                    55399 non-null int64
StratificationType          55399 non-null object
Greater_Risk_Probability    55399 non-null float64
dtypes: float64(2), int64(7), object(6)
memory usage: 6.3+ MB

In [27]:
### label encoding
### LocationDesc, Greater_Risk_Question, Sex, Race, QuestionCode, StratificationType
df_encoded = df.copy()

from sklearn.preprocessing import LabelEncoder
encoders = {}
for clm in ['LocationDesc', 'Greater_Risk_Question', 'Sex', 'Race', 'QuestionCode', 'StratificationType']:
    le = LabelEncoder()
    df_encoded[clm] = le.fit_transform(df_encoded[clm])
    encoders[clm] = le
df_encoded.head()

,Patient_ID,YEAR,LocationDesc,Subtopic,Greater_Risk_Question,Sample_Size,Sex,Race,Grade,QuestionCode,StratID1,StratID2,StratID3,StratificationType,Greater_Risk_Probability
0,1,1995,32,1,6,335.0,0,3,4,9,1,4,0,0,7.4793
1,2,1997,32,0,0,382.0,2,2,4,2,0,3,0,0,49.6852
2,3,1993,54,0,14,196.0,0,7,0,1,1,6,2,3,47.8132
3,4,2017,71,1,6,104.0,1,1,4,9,2,2,0,3,3.4554
4,5,2007,77,1,5,100.0,0,4,4,15,1,7,0,0,0.0000

In [32]:
from sklearn.preprocessing import MinMaxScaler
df_scaled = df_encoded.copy()
scaler = {}
for clm in ['YEAR', 'LocationDesc', 'Subtopic', 'Greater_Risk_Question', 'Sample_Size', 'Sex', 'Race', 
            'Grade', 'QuestionCode', 'StratID1', 'StratID2', 'StratID3', 'StratificationType']:
    sc = MinMaxScaler()
    df_scaled[clm] = sc.fit_transform(df_scaled[clm].values.reshape(-1, 1))
    scaler[clm] = sc

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)

In [33]:
df_scaled.head()

,Patient_ID,YEAR,LocationDesc,Subtopic,Greater_Risk_Question,Sample_Size,Sex,Race,Grade,QuestionCode,StratID1,StratID2,StratID3,StratificationType,Greater_Risk_Probability
0,1,0.153846,0.355556,1.0,0.315789,0.005316,0.0,0.428571,1.0,0.473684,0.5,0.571429,0.0,0.00,7.4793
1,2,0.230769,0.355556,0.0,0.000000,0.006192,1.0,0.285714,1.0,0.105263,0.0,0.428571,0.0,0.00,49.6852
2,3,0.076923,0.600000,0.0,0.736842,0.002723,0.0,1.000000,0.0,0.052632,0.5,0.857143,0.5,0.75,47.8132
3,4,1.000000,0.788889,1.0,0.315789,0.001007,0.5,0.142857,1.0,0.473684,1.0,0.285714,0.0,0.75,3.4554
4,5,0.615385,0.855556,1.0,0.263158,0.000933,0.0,0.571429,1.0,0.789474,0.5,1.000000,0.0,0.00,0.0000

In [34]:
X = df_scaled[['YEAR', 'LocationDesc', 'Subtopic', 'Greater_Risk_Question', 'Sample_Size', 'Sex', 'Race', 
            'Grade', 'QuestionCode', 'StratID1', 'StratID2', 'StratID3', 'StratificationType']]
Y = df_scaled[['Greater_Risk_Probability']]

In [35]:
X.head()

,YEAR,LocationDesc,Subtopic,Greater_Risk_Question,Sample_Size,Sex,Race,Grade,QuestionCode,StratID1,StratID2,StratID3,StratificationType
0,0.153846,0.355556,1.0,0.315789,0.005316,0.0,0.428571,1.0,0.473684,0.5,0.571429,0.0,0.00
1,0.230769,0.355556,0.0,0.000000,0.006192,1.0,0.285714,1.0,0.105263,0.0,0.428571,0.0,0.00
2,0.076923,0.600000,0.0,0.736842,0.002723,0.0,1.000000,0.0,0.052632,0.5,0.857143,0.5,0.75
3,1.000000,0.788889,1.0,0.315789,0.001007,0.5,0.142857,1.0,0.473684,1.0,0.285714,0.0,0.75
4,0.615385,0.855556,1.0,0.263158,0.000933,0.0,0.571429,1.0,0.789474,0.5,1.000000,0.0,0.00

In [36]:
Y.head()

   Greater_Risk_Probability
0                    7.4793
1                   49.6852
2                   47.8132
3                    3.4554
4                    0.0000

In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.20, random_state=42)

In [38]:
from sklearn.neural_network import MLPRegressor
nn = MLPRegressor()
nn

MLPRegressor(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [39]:
nn.fit(X=X_train, y=y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:1316: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)

MLPRegressor(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [40]:
print('train:', nn.score(X_train, y_train))
print('test:', nn.score(X_test, y_test))

train: 0.8976057289766325
test: 0.8977704823512874

In [59]:
nn1 = MLPRegressor(hidden_layer_sizes=(15,30,30,15,), verbose=True, max_iter=1500)
nn1

MLPRegressor(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(15, 30, 30, 15), learning_rate='constant',
       learning_rate_init=0.001, max_iter=1500, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=True, warm_start=False)

In [60]:
nn1.fit(X=X_train, y=y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:1316: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Iteration 1, loss = 291.11118539
Iteration 2, loss = 111.19571690
Iteration 3, loss = 85.76927653
Iteration 4, loss = 66.94281886
Iteration 5, loss = 50.17685893
Iteration 6, loss = 38.79830087
Iteration 7, loss = 34.11067029
Iteration 8, loss = 32.60927046
Iteration 9, loss = 31.56729267
Iteration 10, loss = 30.93780013
Iteration 11, loss = 30.39996804
Iteration 12, loss = 29.94229939
Iteration 13, loss = 29.56896251
Iteration 14, loss = 29.16659345
Iteration 15, loss = 28.84473403
Iteration 16, loss = 28.28154741
Iteration 17, loss = 28.06862614
Iteration 18, loss = 27.68383617
Iteration 19, loss = 27.43829018
Iteration 20, loss = 27.36657684
Iteration 21, loss = 26.93431796
Iteration 22, loss = 27.04566606
Iteration 23, loss = 27.04356064
Iteration 24, loss = 26.55458754
Iteration 25, loss = 26.49170144
Iteration 26, loss = 26.52809194
Iteration 27, loss = 26.32585499
Iteration 28, loss = 26.20995041
Iteration 29, loss = 26.14362204
Iteration 30, loss = 26.20512508
Iteration 31, loss = 26.08931548
Iteration 32, loss = 25.98568545
Iteration 33, loss = 25.85794918
Iteration 34, loss = 25.93106653
Iteration 35, loss = 25.67225417
Iteration 36, loss = 25.83592276
Iteration 37, loss = 25.69301774
Iteration 38, loss = 25.66005839
Iteration 39, loss = 25.62676621
Iteration 40, loss = 25.48533327
Iteration 41, loss = 25.63458940
Iteration 42, loss = 25.44178709
Iteration 43, loss = 25.24784340
Iteration 44, loss = 25.26989590
Iteration 45, loss = 25.22209427
Iteration 46, loss = 25.32134183
Iteration 47, loss = 25.18687166
Iteration 48, loss = 24.92533770
Iteration 49, loss = 24.97268245
Iteration 50, loss = 25.10772644
Iteration 51, loss = 24.83186803
Iteration 52, loss = 24.75156433
Iteration 53, loss = 24.79787338
Iteration 54, loss = 24.65622196
Iteration 55, loss = 24.65861670
Iteration 56, loss = 24.60542223
Iteration 57, loss = 24.62282257
Iteration 58, loss = 24.56539322
Iteration 59, loss = 24.35443419
Iteration 60, loss = 24.19992070
Iteration 61, loss = 24.30764314
Iteration 62, loss = 24.21802039
Iteration 63, loss = 24.20344907
Iteration 64, loss = 24.12611123
Iteration 65, loss = 24.08647291
Iteration 66, loss = 24.05178760
Iteration 67, loss = 23.96888027
Iteration 68, loss = 24.06627905
Iteration 69, loss = 24.16252523
Iteration 70, loss = 23.95279888
Iteration 71, loss = 24.04957965
Iteration 72, loss = 23.77727361
Iteration 73, loss = 23.73607595
Iteration 74, loss = 23.76283256
Iteration 75, loss = 23.72804295
Iteration 76, loss = 23.82661568
Iteration 77, loss = 23.57884983
Iteration 78, loss = 23.70924187
Iteration 79, loss = 23.61739365
Iteration 80, loss = 23.48092360
Iteration 81, loss = 23.44486190
Iteration 82, loss = 23.43295857
Iteration 83, loss = 23.39354582
Iteration 84, loss = 23.36091973
Iteration 85, loss = 23.36862546
Iteration 86, loss = 23.43858395
Iteration 87, loss = 23.14882192
Iteration 88, loss = 23.10586925
Iteration 89, loss = 23.05785281
Iteration 90, loss = 23.06448378
Iteration 91, loss = 22.95966653
Iteration 92, loss = 23.05878210
Iteration 93, loss = 22.96348810
Iteration 94, loss = 22.97988953
Iteration 95, loss = 22.87106040
Iteration 96, loss = 22.91687303
Iteration 97, loss = 22.82107634
Iteration 98, loss = 22.65626672
Iteration 99, loss = 22.74663562
Iteration 100, loss = 22.74224010
Iteration 101, loss = 22.58027372
Iteration 102, loss = 22.42666595
Iteration 103, loss = 22.48355270
Iteration 104, loss = 22.49517256
Iteration 105, loss = 22.59776585
Iteration 106, loss = 22.47396775
Iteration 107, loss = 22.40698898
Iteration 108, loss = 22.44206986
Iteration 109, loss = 22.29557937
Iteration 110, loss = 22.34916971
Iteration 111, loss = 22.26039263
Iteration 112, loss = 22.22311056
Iteration 113, loss = 22.20340926
Iteration 114, loss = 22.22197103
Iteration 115, loss = 22.24693789
Iteration 116, loss = 22.26372875
Iteration 117, loss = 22.12189842
Iteration 118, loss = 22.15773727
Iteration 119, loss = 22.17756530
Iteration 120, loss = 21.98584327
Iteration 121, loss = 22.12610093
Iteration 122, loss = 22.05325119
Iteration 123, loss = 22.03649376
Iteration 124, loss = 22.03038690
Iteration 125, loss = 22.04930253
Iteration 126, loss = 21.98126681
Iteration 127, loss = 22.02613640
Iteration 128, loss = 21.81168374
Iteration 129, loss = 22.00034047
Iteration 130, loss = 21.83724547
Iteration 131, loss = 21.86926866
Iteration 132, loss = 21.76316552
Iteration 133, loss = 21.79756422
Iteration 134, loss = 21.70308080
Iteration 135, loss = 21.79179224
Iteration 136, loss = 21.76963080
Iteration 137, loss = 21.78116119
Iteration 138, loss = 21.64708242
Iteration 139, loss = 21.83781239
Iteration 140, loss = 21.70772666
Iteration 141, loss = 21.59382111
Iteration 142, loss = 21.75255603
Iteration 143, loss = 21.58531515
Iteration 144, loss = 21.66319722
Iteration 145, loss = 21.50509455
Iteration 146, loss = 21.53764715
Iteration 147, loss = 21.57172200
Iteration 148, loss = 21.54223633
Iteration 149, loss = 21.56490116
Iteration 150, loss = 21.54135641
Iteration 151, loss = 21.51792296
Iteration 152, loss = 21.36541338
Iteration 153, loss = 21.52071504
Iteration 154, loss = 21.56889123
Iteration 155, loss = 21.39960808
Iteration 156, loss = 21.44363541
Iteration 157, loss = 21.58387797
Iteration 158, loss = 21.32440819
Iteration 159, loss = 21.37221771
Iteration 160, loss = 21.33989934
Iteration 161, loss = 21.31099784
Iteration 162, loss = 21.42633877
Iteration 163, loss = 21.44803616
Iteration 164, loss = 21.29217904
Iteration 165, loss = 21.31847007
Iteration 166, loss = 21.31724466
Iteration 167, loss = 21.27940790
Iteration 168, loss = 21.33237105
Iteration 169, loss = 21.29711978
Iteration 170, loss = 21.16662472
Iteration 171, loss = 21.19412635
Iteration 172, loss = 21.33000378
Iteration 173, loss = 21.19016483
Iteration 174, loss = 21.30466504
Iteration 175, loss = 21.13171440
Iteration 176, loss = 21.08326307
Iteration 177, loss = 21.11470747
Iteration 178, loss = 21.07802606
Iteration 179, loss = 21.06595439
Iteration 180, loss = 21.17631090
Iteration 181, loss = 21.07000505
Iteration 182, loss = 21.10252111
Iteration 183, loss = 21.06137993
Iteration 184, loss = 21.05713923
Iteration 185, loss = 21.01343702
Iteration 186, loss = 21.18132448
Iteration 187, loss = 21.18158519
Iteration 188, loss = 21.06104582
Iteration 189, loss = 20.98937719
Iteration 190, loss = 21.00013142
Iteration 191, loss = 20.89568060
Iteration 192, loss = 20.97661729
Iteration 193, loss = 20.97609375
Iteration 194, loss = 20.92261590
Iteration 195, loss = 20.97574928
Iteration 196, loss = 20.89828209
Iteration 197, loss = 20.87985252
Iteration 198, loss = 20.88735173
Iteration 199, loss = 21.01782504
Iteration 200, loss = 20.76278058
Iteration 201, loss = 20.86034255
Iteration 202, loss = 20.86563341
Iteration 203, loss = 20.93452809
Iteration 204, loss = 20.82731191
Iteration 205, loss = 20.84382832
Iteration 206, loss = 20.75698130
Iteration 207, loss = 20.79253207
Iteration 208, loss = 20.74645296
Iteration 209, loss = 20.86376867
Iteration 210, loss = 20.86347223
Iteration 211, loss = 20.77246149
Iteration 212, loss = 20.79982507
Iteration 213, loss = 20.65685220
Iteration 214, loss = 20.65929189
Iteration 215, loss = 20.56402457
Iteration 216, loss = 20.75608960
Iteration 217, loss = 20.73123501
Iteration 218, loss = 20.62188650
Iteration 219, loss = 20.59188055
Iteration 220, loss = 20.60205678
Iteration 221, loss = 20.52914270
Iteration 222, loss = 20.63941627
Iteration 223, loss = 20.55606820
Iteration 224, loss = 20.48662789
Iteration 225, loss = 20.49962891
Iteration 226, loss = 20.46580511
Iteration 227, loss = 20.67839788
Iteration 228, loss = 20.47542205
Iteration 229, loss = 20.48872708
Iteration 230, loss = 20.46233436
Iteration 231, loss = 20.39654157
Iteration 232, loss = 20.33174590
Iteration 233, loss = 20.35082301
Iteration 234, loss = 20.39458076
Iteration 235, loss = 20.44622173
Iteration 236, loss = 20.23400921
Iteration 237, loss = 20.30552020
Iteration 238, loss = 20.31975172
Iteration 239, loss = 20.21417981
Iteration 240, loss = 20.23457842
Iteration 241, loss = 20.24415808
Iteration 242, loss = 20.32207031
Iteration 243, loss = 20.23897600
Iteration 244, loss = 20.14514404
Iteration 245, loss = 20.15096937

Iteration 246, loss = 20.28629836
Iteration 247, loss = 20.18906700
Iteration 248, loss = 20.07564624
Iteration 249, loss = 20.03571431
Iteration 250, loss = 20.21677979
Iteration 251, loss = 20.20592963
Iteration 252, loss = 20.21665941
Iteration 253, loss = 20.12738203
Iteration 254, loss = 20.16582300
Iteration 255, loss = 19.96607057
Iteration 256, loss = 20.14458299
Iteration 257, loss = 19.99837850
Iteration 258, loss = 20.04211036
Iteration 259, loss = 20.09245577
Iteration 260, loss = 20.08210604
Iteration 261, loss = 20.02674089
Iteration 262, loss = 19.95954349
Iteration 263, loss = 19.93169317
Iteration 264, loss = 20.03185234
Iteration 265, loss = 19.97503615
Iteration 266, loss = 19.83051273
Iteration 267, loss = 19.95198907
Iteration 268, loss = 19.96926569
Iteration 269, loss = 20.03633407
Iteration 270, loss = 19.86965639
Iteration 271, loss = 19.99230682
Iteration 272, loss = 19.87800078
Iteration 273, loss = 20.02566203
Iteration 274, loss = 19.91721366
Iteration 275, loss = 19.75913163
Iteration 276, loss = 19.80677666
Iteration 277, loss = 19.89870316
Iteration 278, loss = 19.82617821
Iteration 279, loss = 19.80402243
Iteration 280, loss = 19.76610916
Iteration 281, loss = 19.97172876
Iteration 282, loss = 19.85774324
Iteration 283, loss = 19.75898311
Iteration 284, loss = 19.85844792
Iteration 285, loss = 19.72699114
Iteration 286, loss = 19.84129659
Iteration 287, loss = 19.72581586
Iteration 288, loss = 19.70877658
Iteration 289, loss = 19.83574235
Iteration 290, loss = 19.79718058
Iteration 291, loss = 19.69469430
Iteration 292, loss = 19.65739591
Iteration 293, loss = 19.78353767
Iteration 294, loss = 19.75125307
Iteration 295, loss = 19.69890132
Iteration 296, loss = 19.73170018
Iteration 297, loss = 19.64819202
Iteration 298, loss = 19.65432064
Iteration 299, loss = 19.64343044
Iteration 300, loss = 19.68283862
Iteration 301, loss = 19.74205107
Iteration 302, loss = 19.75408089
Iteration 303, loss = 19.69004148
Iteration 304, loss = 19.76157568
Iteration 305, loss = 19.64768084
Iteration 306, loss = 19.66328078
Iteration 307, loss = 19.61403260
Iteration 308, loss = 19.59730719
Iteration 309, loss = 19.70982748
Iteration 310, loss = 19.61525176
Iteration 311, loss = 19.50099782
Iteration 312, loss = 19.63416953
Iteration 313, loss = 19.63048637
Iteration 314, loss = 19.60019454
Iteration 315, loss = 19.58464046
Iteration 316, loss = 19.76782932
Iteration 317, loss = 19.57895296
Iteration 318, loss = 19.66891403
Iteration 319, loss = 19.50501581
Iteration 320, loss = 19.52320642
Iteration 321, loss = 19.56707767
Iteration 322, loss = 19.53794932
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.

MLPRegressor(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(15, 30, 30, 15), learning_rate='constant',
       learning_rate_init=0.001, max_iter=1500, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=True, warm_start=False)

In [61]:
print('train:', nn1.score(X_train, y_train))
print('test:', nn1.score(X_test, y_test))

train: 0.9078855153704022
test: 0.9047711222413232

In [64]:
from keras.models import Sequential
from keras.layers import Dense

In [75]:
model = Sequential()
model.add(Dense(13, input_dim=13, activation='relu'))
model.add(Dense(1, activation='linear'))

In [76]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_5 (Dense)              (None, 13)                182
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 14
=================================================================
Total params: 196
Trainable params: 196
Non-trainable params: 0
_________________________________________________________________

In [77]:
# Compile model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [78]:
model.fit(X_train, y_train, epochs=5, batch_size=1)

Epoch 1/5
44319/44319 [==============================] - 31s 696us/step - loss: -371.5006 - acc: 2.2564e-05
Epoch 2/5
44319/44319 [==============================] - 30s 676us/step - loss: -372.7467 - acc: 0.0000e+00
Epoch 3/5
44319/44319 [==============================] - 31s 695us/step - loss: -372.7467 - acc: 0.0000e+00
Epoch 4/5
44319/44319 [==============================] - 30s 671us/step - loss: -372.7467 - acc: 0.0000e+00
Epoch 5/5
44319/44319 [==============================] - 31s 690us/step - loss: -372.7467 - acc: 0.0000e+00

In [79]:
scores = model.evaluate(X_train, y_train)
print("Train: %s: %.2f%%" % (model.metrics_names[1], scores[1]*100))
scores = model.evaluate(X_test, y_test)
print("Train: %s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

44319/44319 [==============================] - 1s 12us/step
Train: acc: 0.00%
11080/11080 [==============================] - 0s 11us/step
Train: acc: 0.00%

In [82]:
model.predict(X_train)

array([[2.8502254],
       [2.0438976],
       [2.2928386],
       ...,
       [2.4994478],
       [1.7685976],
       [2.5492425]], dtype=float32)